server:
  port: 8762
spring:
  application:
    name: eureka1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false
  instance:
      prefer-ip-address: true