server:
  port: 8002
spring:
  application:
    name: dept1
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
      url: jdbc:mysql://localhost:3306/clouddb02             # 数据库名称
      username: root
      password: root
      dbcp2:
        min-idle: 300                                          # 数据库连接池的最小维持连接数
        initial-size: 300                                      # 初始化连接数
        max-total: 300                                         # 最大连接数
        max-wait-millis: 2000                                  # 等待连接获取的最大超时时间


mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml   #mapper映射文件所在的位置
  type-aliases-package: com.offcn.msg.enty            #enty别名类所在的包
  config-location: classpath:/mybatis/mybatis.xml     #mybatis配置文件所在的位置


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true






